### ISSUE TITLE
Code issue in evaluate_depth_dynamic.py

### ISSUE THREAD

**Issue by LeeWonJoon9868** [xingy038/DS-Depth#2]
Thank you for releasing the code for your project. It was an interesting read.

In the evaluate_depth_dynamic.py, 419 line, I guess the segmentation mask for dynamic moving object is loaded in the wrong way. 

Under the code you have released, the same mask (the last mask for cityscapes test) will be used for all the evaluation.

The mask should be saved after 198 line and be used in 419 line. 

Can you check if it is wrong? 

Thank you!

**Comment by xingy038** [comment]
Hi,

I roughly reviewed this code. 198 and 419 line are in the same function. The data loader (there are two data loaders in this rep) loads the dynamic moving object and 419 line has a loop controlled by pred_disps. Because this code has been completed for a long time, the previously used server lost a lot of raw data due to a crash, and I could not view the code that had not been cleaned up. You can try to evaluate the model, if the load is the same frame of mask, then the error should be very large.
